### ISSUE TITLE
Can't instantiate actor when props defined with Props(classOf[Foo])

### ISSUE THREAD

**Issue by rockjam** [unicredit/akka.js#54] opened 2016-09-22 12:29 UTC
Playing around with akka.js at https://scalafiddle.io I noticed a problem with actor instantiation.

This one works fine. Link to fiddle: https://scalafiddle.io/sf/h8XVHMe/0

```
import akka.actor._

object ShoutBox  {
  def props: Props = Props(new ShoutBox)
}

final class ShoutBox extends Actor {

  override def receive: Receive = {
    case x: String  => println(x.toUpperCase)
  }

}

val system = ActorSystem()

val shout = system.actorOf(ShoutBox.props)
println("Shoutbox created")

shout ! "hello"
shout ! "world"
```

This one doesn't work. Link to fiddle: https://scalafiddle.io/sf/luBGLkI/1

```

import akka.actor._

object ShoutBox  {
  def props: Props = Props(classOf[ShoutBox])
}

final class ShoutBox extends Actor {

  override def receive: Receive = {
    case x: String  => println(x.toUpperCase)
  }

}

val system = ActorSystem()

val shout = system.actorOf(ShoutBox.props)
println("Shoutbox created")

shout ! "hello"
shout ! "world"
```

Can somebody clarify, is this behaviour right, or both ways should work?

**Comment by andreaTP** [comment] 2016-09-22 19:05
I wait long enough for this issue to be opened! Seriously, thanks a lot @rockjam !
I always forget to mention this caveat, probably I'll need to write a dedicated section in `Readme`.

The problem here is that in Scala.Js cannot retrieve the name of the underlying `T` exported name from a `Class[T]`. On JVM this is easy due to reflection... (@sjrd can correct me if I'm wrong )
So the current approach is to store in a Map the bindings between matching strings and Classes.

So what is needed here is to add to that map the proper entry to get the job done using

``` scala
akka.actor.JSDynamicAccess.injectClass("TClassName" -> classOf[T])
```

Said that everything work in this: https://scalafiddle.io/sf/YbJgRwZ/1 (Scala -> show template for the full content).
Unfortunately I think there is a bug resolving the string name within the ScalaFiddle object, I need to dig into this or @sjrd can help here :-)

Thanks a lot for rising the issue!

**Comment by sjrd** [comment] 2016-09-22 21:40
> The problem here is that in Scala.Js cannot retrieve the name of the underlying `T` exported name from a `Class[T]`.

Do you mean `clazz.getName()`? That is supported in Scala.js. At least as long as the user doesn't change the information with `scalaJSSemantics ~= { _.withRuntimeClassName(...) }`.

**Comment by sjrd** [comment] 2016-09-22 21:42
Note that Fiddle, with the default template, wraps your code in a top-level object; so the apparent name of your classes are artificially namespaced in that top-level object. This could explain the "bug" with resolving the string name (I didn't fully get what it was).

**Comment by andreaTP** [comment] 2016-09-23 10:40
ok, got it the problem is evident here:
https://scalafiddle.io/sf/YbJgRwZ/2

you cannot export the inner object so it cannot be loaded at runtime via name resolving.

I'm wondering why the error is triggered only if I explicit `JSExport` annotation and not if the class is targeted by a `JSExportDescendentClasses` from `Actor` trait.

I definitely need to write some docs on this.

**Comment by sjrd** [comment] 2016-09-23 11:16
> I'm wondering why the error is triggered only if I explicit JSExport annotation and not if the class is targeted by a JSExportDescendentClasses from Actor trait.

Maybe because you set `ignoreInvalidDescendants = true` in `JSExportDescendantClasses`. This setting silently ignores descendant classes which cannot be exported, instead of reporting errors.

**Comment by andreaTP** [comment] 2016-09-23 11:50
uh
yes, there are inner class in Akka itself that cannot be exported :-(

**Comment by rockjam** [comment] 2016-09-23 12:36
@andreaTP @sjrd Thanks for clarification. It was not obvious at first, cause previously I used `classOf[Foo]` in scala.js without any problem

**Comment by andreaTP** [comment] 2016-10-03 08:11
Explained in Readme, I'll close this.

**Closed as completed by andreaTP** 2016-10-03 08:11 UTC
