### ISSUE TITLE
Got linking errors when doing fastOptJS on Sink.preMaterialize

### ISSUE THREAD

**Issue by pishen** [unicredit/akka.js#89] opened 2018-08-08 15:47 UTC
I got the following linking errors when running `fastOptJS`

```
[error] Referring to non-existent class scala.compat.java8.OptionConverters$RichOptionForJava8$
[error]   called from akka.stream.Attributes.getAttribute(java.lang.Class)java.util.Optional
[error]   called from akka.stream.Attributes.getAttribute(java.lang.Class,akka.stream.Attributes$Attribute)akka.stream.Attributes$Attribute
[error]   called from akka.stream.impl.QueueSink$$anon$1.<init>(akka.stream.impl.QueueSink,akka.stream.Attributes)
[error]   called from akka.stream.impl.QueueSink.createLogicAndMaterializedValue(akka.stream.Attributes)scala.Tuple2
[error]   called from akka.stream.impl.GraphStageIsland.materializeAtomic(akka.stream.impl.StreamLayout$AtomicModule,akka.stream.Attributes)scala.Tuple2
[error]   called from akka.stream.impl.PhasedFusingActorMaterializer.materialize(akka.stream.Graph,akka.stream.Attributes,akka.stream.impl.Phase,scala.collection.immutable.Map)java.lang.Object
[error]   called from akka.stream.impl.PhasedFusingActorMaterializer.materialize(akka.stream.Graph,akka.stream.Attributes)java.lang.Object
[error]   called from akka.stream.impl.PhasedFusingActorMaterializer.materialize(akka.stream.Graph)java.lang.Object
[error]   called from akka.stream.scaladsl.RunnableGraph.run(akka.stream.Materializer)java.lang.Object
[error]   called from akka.stream.scaladsl.Sink.preMaterialize(akka.stream.Materializer)scala.Tuple2
[error]   called from Main$.main([java.lang.String)scala.Unit
[error]   called from core module module initializers
[error] involving instantiated classes:
[error]   akka.stream.Attributes
[error]   akka.stream.impl.QueueSink
[error]   akka.stream.impl.GraphStageIsland
[error]   akka.stream.impl.PhasedFusingActorMaterializer
[error]   akka.stream.scaladsl.RunnableGraph
[error]   akka.stream.scaladsl.Sink
[error]   Main$
[error] Referring to non-existent class scala.compat.java8.OptionConverters$
[error]   called from akka.stream.Attributes.getAttribute(java.lang.Class)java.util.Optional
[error]   called from akka.stream.Attributes.getAttribute(java.lang.Class,akka.stream.Attributes$Attribute)akka.stream.Attributes$Attribute
[error]   called from akka.stream.impl.QueueSink$$anon$1.<init>(akka.stream.impl.QueueSink,akka.stream.Attributes)
[error]   called from akka.stream.impl.QueueSink.createLogicAndMaterializedValue(akka.stream.Attributes)scala.Tuple2
[error]   called from akka.stream.impl.GraphStageIsland.materializeAtomic(akka.stream.impl.StreamLayout$AtomicModule,akka.stream.Attributes)scala.Tuple2
[error]   called from akka.stream.impl.PhasedFusingActorMaterializer.materialize(akka.stream.Graph,akka.stream.Attributes,akka.stream.impl.Phase,scala.collection.immutable.Map)java.lang.Object
[error]   called from akka.stream.impl.PhasedFusingActorMaterializer.materialize(akka.stream.Graph,akka.stream.Attributes)java.lang.Object
[error]   called from akka.stream.impl.PhasedFusingActorMaterializer.materialize(akka.stream.Graph)java.lang.Object
[error]   called from akka.stream.scaladsl.RunnableGraph.run(akka.stream.Materializer)java.lang.Object
[error]   called from akka.stream.scaladsl.Sink.preMaterialize(akka.stream.Materializer)scala.Tuple2
[error]   called from Main$.main([java.lang.String)scala.Unit
[error]   called from core module module initializers
[error] involving instantiated classes:
[error]   akka.stream.Attributes
[error]   akka.stream.impl.QueueSink
[error]   akka.stream.impl.GraphStageIsland
[error]   akka.stream.impl.PhasedFusingActorMaterializer
[error]   akka.stream.scaladsl.RunnableGraph
[error]   akka.stream.scaladsl.Sink
[error]   Main$
[error] Referring to non-existent method scala.compat.java8.OptionConverters$.RichOptionForJava8(scala.Option)scala.Option
[error]   called from akka.stream.Attributes.getAttribute(java.lang.Class)java.util.Optional
[error]   called from akka.stream.Attributes.getAttribute(java.lang.Class,akka.stream.Attributes$Attribute)akka.stream.Attributes$Attribute
[error]   called from akka.stream.impl.QueueSink$$anon$1.<init>(akka.stream.impl.QueueSink,akka.stream.Attributes)
[error]   called from akka.stream.impl.QueueSink.createLogicAndMaterializedValue(akka.stream.Attributes)scala.Tuple2
[error]   called from akka.stream.impl.GraphStageIsland.materializeAtomic(akka.stream.impl.StreamLayout$AtomicModule,akka.stream.Attributes)scala.Tuple2
[error]   called from akka.stream.impl.PhasedFusingActorMaterializer.materialize(akka.stream.Graph,akka.stream.Attributes,akka.stream.impl.Phase,scala.collection.immutable.Map)java.lang.Object
[error]   called from akka.stream.impl.PhasedFusingActorMaterializer.materialize(akka.stream.Graph,akka.stream.Attributes)java.lang.Object
[error]   called from akka.stream.impl.PhasedFusingActorMaterializer.materialize(akka.stream.Graph)java.lang.Object
[error]   called from akka.stream.scaladsl.RunnableGraph.run(akka.stream.Materializer)java.lang.Object
[error]   called from akka.stream.scaladsl.Sink.preMaterialize(akka.stream.Materializer)scala.Tuple2
[error]   called from Main$.main([java.lang.String)scala.Unit
[error]   called from core module module initializers
[error] involving instantiated classes:
[error]   akka.stream.Attributes
[error]   akka.stream.impl.QueueSink
[error]   akka.stream.impl.GraphStageIsland
[error]   akka.stream.impl.PhasedFusingActorMaterializer
[error]   akka.stream.scaladsl.RunnableGraph
[error]   akka.stream.scaladsl.Sink
[error]   Main$
[error] Referring to non-existent method scala.compat.java8.OptionConverters$RichOptionForJava8$.asJava$extension(scala.Option)java.util.Optional
[error]   called from akka.stream.Attributes.getAttribute(java.lang.Class)java.util.Optional
[error]   called from akka.stream.Attributes.getAttribute(java.lang.Class,akka.stream.Attributes$Attribute)akka.stream.Attributes$Attribute
[error]   called from akka.stream.impl.QueueSink$$anon$1.<init>(akka.stream.impl.QueueSink,akka.stream.Attributes)
[error]   called from akka.stream.impl.QueueSink.createLogicAndMaterializedValue(akka.stream.Attributes)scala.Tuple2
[error]   called from akka.stream.impl.GraphStageIsland.materializeAtomic(akka.stream.impl.StreamLayout$AtomicModule,akka.stream.Attributes)scala.Tuple2
[error]   called from akka.stream.impl.PhasedFusingActorMaterializer.materialize(akka.stream.Graph,akka.stream.Attributes,akka.stream.impl.Phase,scala.collection.immutable.Map)java.lang.Object
[error]   called from akka.stream.impl.PhasedFusingActorMaterializer.materialize(akka.stream.Graph,akka.stream.Attributes)java.lang.Object
[error]   called from akka.stream.impl.PhasedFusingActorMaterializer.materialize(akka.stream.Graph)java.lang.Object
[error]   called from akka.stream.scaladsl.RunnableGraph.run(akka.stream.Materializer)java.lang.Object
[error]   called from akka.stream.scaladsl.Sink.preMaterialize(akka.stream.Materializer)scala.Tuple2
[error]   called from Main$.main([java.lang.String)scala.Unit
[error]   called from core module module initializers
[error] involving instantiated classes:
[error]   akka.stream.Attributes
[error]   akka.stream.impl.QueueSink
[error]   akka.stream.impl.GraphStageIsland
[error]   akka.stream.impl.PhasedFusingActorMaterializer
[error]   akka.stream.scaladsl.RunnableGraph
[error]   akka.stream.scaladsl.Sink
[error]   Main$
[error] org.scalajs.core.tools.linker.LinkingException: There were linking errors
[error] 	at org.scalajs.core.tools.linker.frontend.BaseLinker.linkInternal(BaseLinker.scala:160)
[error] 	at org.scalajs.core.tools.linker.frontend.BaseLinker.linkInternal(BaseLinker.scala:108)
[error] 	at org.scalajs.core.tools.linker.frontend.LinkerFrontend.$anonfun$link$3(LinkerFrontend.scala:63)
[error] 	at org.scalajs.core.tools.logging.Logger.time(Logger.scala:28)
[error] 	at org.scalajs.core.tools.logging.Logger.time$(Logger.scala:26)
[error] 	at org.scalajs.sbtplugin.Loggers$SbtLoggerWrapper.time(Loggers.scala:7)
[error] 	at org.scalajs.core.tools.linker.frontend.LinkerFrontend.link(LinkerFrontend.scala:62)
[error] 	at org.scalajs.core.tools.linker.Linker.$anonfun$link$1(Linker.scala:52)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at org.scalajs.core.tools.linker.Linker.guard(Linker.scala:69)
[error] 	at org.scalajs.core.tools.linker.Linker.link(Linker.scala:50)
[error] 	at org.scalajs.core.tools.linker.ClearableLinker.$anonfun$link$1(ClearableLinker.scala:52)
[error] 	at org.scalajs.core.tools.linker.ClearableLinker.$anonfun$link$1$adapted(ClearableLinker.scala:52)
[error] 	at org.scalajs.core.tools.linker.ClearableLinker.linkerOp(ClearableLinker.scala:63)
[error] 	at org.scalajs.core.tools.linker.ClearableLinker.link(ClearableLinker.scala:52)
[error] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSStageSettings$11(ScalaJSPluginInternal.scala:315)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$1(FileFunction.scala:73)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$4(FileFunction.scala:147)
[error] 	at sbt.util.Difference.apply(Tracked.scala:313)
[error] 	at sbt.util.Difference.apply(Tracked.scala:293)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$3(FileFunction.scala:143)
[error] 	at sbt.util.Difference.apply(Tracked.scala:313)
[error] 	at sbt.util.Difference.apply(Tracked.scala:288)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$2(FileFunction.scala:142)
[error] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSStageSettings$10(ScalaJSPluginInternal.scala:320)
[error] 	at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:272)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
```
The code is a simple main function which calls `preMaterialize` on a `Sink`:
```scala
object Main {
  def main(args: Array[String]): Unit = {
    implicit val system = ActorSystem("QuickStart")
    implicit val materializer = ActorMaterializer()

    Sink.queue[Int].preMaterialize
  }
}
```
I'm using Scala.js 0.6.24 and akkajsactorstream 1.2.5.14, with `scalaJSUseMainModuleInitializer` set to `true`.

A full example is available at https://github.com/pishen/akka-js-test

**Comment by andreaTP** [comment] 2018-08-08 18:51
Thanks for the report, I'll look into this tomorrow.

**Comment by andreaTP** [comment] 2018-08-09 10:32
This is the root cause of the problem:
https://github.com/akka-js/akka.js/commit/cd7af70b3b24a870da39c74739244372d154e9ef#diff-376ba1e63c194d77b18f5409e78c5c58R77

you have a temporary fix here: https://github.com/akka-js/akka.js/tree/fixLinking
(you can eventually `publishLocal` from that branch).

And a PR in Akka upstream to fix the root cause:
https://github.com/akka/akka/pull/25456

**Comment by pishen** [comment] 2018-08-09 10:42
Great! I use the `Sink.actorRef` way for now, which doesn't need `preMaterialize` and doesn't seem to cause the problem.

Thank you for the investigation!

**Comment by andreaTP** [comment] 2018-08-24 20:26
I close this releasing `1.2.5.15` that contains the upstream fix.thanks a lot for reporting!

**Closed as completed by andreaTP** 2018-08-24 20:26 UTC
