### ISSUE TITLE
Non-Existant method SimpleDateFormat

### ISSUE THREAD

**Issue by LogicalTime** [unicredit/akka.js#62] opened 2017-02-02 22:39 UTC
I'm getting an error just starting up an ActorSystem.
Referring to non-existant method java.text.SimpleDateFormat.format(java.util.Date)
called from akka.event.Logging...timestamp(...)
Using scalajs 0.6.14 and akkajs 0.2.4.16

**Comment by andreaTP** [comment] 2017-02-03 13:02
Hi, thanks for reporting!
I updated the "pingpong" example here: https://github.com/akka-js/akka.js-examples/tree/versBump/pingpong
and it does work, are you able to share a repro?

**Comment by LogicalTime** [comment] 2017-02-03 18:11
My build is a bit rediculous.  I bet that class is being fast optimized out. Either that or the Java.time  port to Scalajs is over shadowing it or something. When I make the simple date format myself and stick it in my  blocksjs project the actor system starts up fine. So no worries. Maybe the simple date format shouldn't go in the Java.txt package though?

**Comment by andreaTP** [comment] 2017-02-04 07:15
SimpleDateFormat is a dummy implementation in the Akka.js codebase, so as far as you have the rest even it should be reachable. Are you importing another Java.time implementation for Sjs? You really don't need to implement it yourself and if your file exists probably it shadows Akka.js provided one.

**Comment by LogicalTime** [comment] 2017-02-04 12:32
Using https://github.com/cquiroz/scala-java-time

**Comment by andreaTP** [comment] 2017-02-04 20:22
should not be the problem, namespaces are different...
If you can produce a minimal repro I will be happy to dig!

**Comment by andreaTP** [comment] 2017-02-04 20:23
more over in scala-java-time there is no implementation of SimpleDateFormat AFAIK

**Comment by andreaTP** [comment] 2017-02-15 10:08
any update on this?

**Comment by andreaTP** [comment] 2017-02-20 08:13
In case we cannot reproduce the bug I think we can close this issue ... @LogicalTime

**Closed as completed** 2017-02-26 12:25 UTC
